I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 237, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/script.rpy", line 23, in script
    show splash at (.5,.5)
TypeError: 'tuple' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 237, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/script.rpy", line 23, in script
    show splash at (.5,.5)
  File "/Users/akpulaski/Applications/renpy-8.1.0-sdk/renpy/ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/Users/akpulaski/Applications/renpy-8.1.0-sdk/renpy/ast.py", line 1391, in show_imspec
    renpy.config.show(name,
  File "/Users/akpulaski/Applications/renpy-8.1.0-sdk/renpy/exports.py", line 745, in show
    img = i(img) # type: ignore
TypeError: 'tuple' object is not callable

macOS-13.6-arm64-arm-64bit arm64
Ren'Py 8.1.1.23060707
Fosc Jo 1.0
Thu Sep 28 18:36:35 2023
